name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.5.0]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean cache
      run: npm cache clean --force
    - name: check env names
      run: echo $process.env.CI
    - name: Env check first time
      run: |
        ls -lrt
        echo $(env) 
    - name: Install Packages
      run: npm install 
    - name: Changing permissions
      run: chmod -R a+rwx ./node_modules 
    - name: Env check
      run: ls -lrt
    - name: Build page
      run: npm run build
      env:
        CI: false
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build